BUILD_DIR:=../erc20/.build

SPEC_NAMES:=proxyType-success \
            proxyType-failure \
            implementation-success \
            implementation-failure \
            changeMasterCopy-success \
            changeMasterCopy-failure-1 \
            changeMasterCopy-failure-2 \
            changeMasterCopy-failure-3 \
            totalSupply-success \
            totalSupply-failure \
            balanceOf-success \
            balanceOf-failure \
            allowance-success \
            allowance-failure \
            approve-success \
            approve-failure \
            transfer-success-1 \
            transfer-success-2 \
            transfer-failure-1 \
            transfer-failure-2 \
            transfer-failure-3 \
            transferFrom-success-1 \
            transferFrom-success-2 \
            transferFrom-failure-1 \
            transferFrom-failure-2 \
            transferFrom-failure-3

include ../resources/kprove.mak
