BUILD_DIR:=../.build

SPEC_GROUP:=gnosis
SPEC_INI:=gnosis-spec.ini

SPEC_NAMES:=encodeTransactionData-data32 \
            encodeTransactionData-data33 \
            signatureSplit-pos0 \
            signatureSplit-pos1 \
            signatureSplit-pos2 \
            checkSignatures-thres-too-large \
            checkSignatures-thres-1-sig-v2-ec0 \
            checkSignatures-thres-1-sig-v2-not-ec0-success \
            checkSignatures-thres-1-sig-v2-not-ec0-notOwner \
            checkSignatures-thres-2-sig-v2-ec0 \
            checkSignatures-thres-2-sig-v2-o0-eq-o1 \
            checkSignatures-thres-2-sig-v2-o0-neq-o1-success \
            checkSignatures-thres-2-sig-v2-o0-neq-o1-failure
              
include ../resources/kprove.mak
