  bash -x run.sh mainnet-specs/01_tether.ini
  bash -x run.sh mainnet-specs/02_bnb.ini
  bash -x run.sh mainnet-specs/04_chainlink.ini
  bash -x run.sh mainnet-specs/05_huobi.ini
  bash -x run.sh mainnet-specs/06_maker.ini
  bash -x run.sh mainnet-specs/08_crypto.ini
  bash -x run.sh mainnet-specs/09_ino.ini
  bash -x run.sh mainnet-specs/10_bat.ini
  bash -x run.sh mainnet-specs/11_insight.ini
  bash -x run.sh mainnet-specs/13_hedg.ini
  bash -x run.sh mainnet-specs/14_zrx.ini
