BUILD_DIR:=../.build

LOCAL_LEMMAS:=abstract-semantics.k verification.k
TMPLS:=../module-tmpl.k ../spec-tmpl.k

SPEC_GROUP:=hobby-erc20
SPEC_INI:=hobby-erc20-spec.ini

SPEC_NAMES:=totalSupply \
            balanceOf \
            allowance \
            approve-success \
            approve-failure \
            transfer-success-1 \
            transfer-success-2 \
            transfer-failure-1 \
            transfer-failure-2 \
            transferFrom-success-1 \
            transferFrom-success-2 \
            transferFrom-failure-1 \
            transferFrom-failure-2

include ../../resources/kprove.mak
