BUILD_DIR:=../../.build

LOCAL_LEMMAS:=../abstract-semantics.k ../verification.k
TMPLS:=../module-tmpl.k ../spec-tmpl.k

SPEC_GROUP:=gnosis-test
SPEC_INI:=api-test.ini

SPEC_NAMES:=testKeccak-data1 \
            testKeccak-data32 \
            testKeccak-data33 \
            testAbiEncode \
            testAbiEncode-AndKeccak-data1 \
            testAbiEncodePacked \
            testEcrecover-non-empty \
            testEcrecover-empty

include ../../resources/kprove.mak
