LOCAL_LEMMAS:=verification.k \
			  ../../resources/abstract-semantics-direct-gas.k \
			  ../../resources/evm-symbolic.k \
			  ../../resources/evm-data-map-symbolic.k

SPEC_INI=../zeppelin/zeppelin-erc20-spec.ini

include ../zeppelin/Makefile
